### PR TITLE
Fix saving and restoring cursor position on macOS Terminal.app

### LINKED ISSUE #15: Save/Restore cursor position not working on macOS Terminal.app
[Our project Garden](https://github.com/garden-io/garden) uses `ansi-escapes` to update CLI output in–place and I just noticed that the cursor is all over the place on the macOS Terminal.app. (See also this [issue from our project](https://github.com/garden-io/garden/issues/1040).)

Using [this suggestion](https://github.com/sindresorhus/ansi-escapes/pull/4#commitcomment-29150267) seems to fix the issue. I'll submit a PR shortly.

### PR DESCRIPTION
**Pull request by eysi09**
Fixes #15 (see issue for details).

Here's an example of our CLI output before the fix:

Screenshot 2019-07-31 at 17 34 06

And here's how it looks with the fix:

Screenshot 2019-07-31 at 17 34 47

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -49,8 +49,8 @@ ansiEscapes.cursorForward = (count = 1) => ESC + count + 'C';
 ansiEscapes.cursorBackward = (count = 1) => ESC + count + 'D';
 
 ansiEscapes.cursorLeft = ESC + 'G';
-ansiEscapes.cursorSavePosition = ESC + (isTerminalApp ? '7' : 's');
-ansiEscapes.cursorRestorePosition = ESC + (isTerminalApp ? '8' : 'u');
+ansiEscapes.cursorSavePosition = ESC + (isTerminalApp ? '\u001B7' : 's');
+ansiEscapes.cursorRestorePosition = ESC + (isTerminalApp ? '\u001B8' : 'u');
```
Comment (sindresorhus) [inline index.js]: I think you want to move `ESC` to the "else" here.

Comment (eysi09) [reply index.js]: Ah yes, good catch. I've updated the PR. And thanks for the quick reply!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ansi-escapes/releases/tag/v4.2.1
